### ISSUE TITLE
Error: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region

### ISSUE THREAD

**Issue by Coding-Fusion** [microsoft/vscode-cosmosdb#1554] opened 2020-06-02 07:37 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

AM: Error: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.

Cloud Skill Challenge error

**Comment by EricJizbaMSFT** [comment] 2020-06-11 22:49
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1510

**Closed by EricJizbaMSFT** 2020-06-11 22:49 UTC
