### ISSUE TITLE
cosmosDB.createAccount

### ISSUE THREAD

**Issue by jmfloreszazo** [microsoft/vscode-cosmosdb#1486] opened 2020-05-21 12:09 UTC
Repro steps:

1. Donwload add-on
2. Register acount
3. Create 

Action: cosmosDB.createAccount
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: d8dbd61f-e2ee-47f3-8151-0b3de4f58f43, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Mi...

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

**Comment by EricJizbaMSFT** [comment] 2020-05-21 19:57
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1472

**Closed by EricJizbaMSFT** 2020-05-21 19:57 UTC
