### ISSUE TITLE
Quering by "$oid" gives error

### ISSUE THREAD

**Issue by dianasotirova** [Microsoft/vscode-cosmosdb#665] opened 2018-06-07 10:35 UTC
Hi,
I am trying to query item by ObjectId using EJSON:

db.items.find({ "_id": { "$oid": "5b0ed0dd03baa16259000020" } }) 

and receive following error:
Can't canonicalize query: BadValue unknown operator: $oid

Azure Cosmos DB Extension Version: 0.7.1
vscode version: 1.24.0

**Comment by PrashanthCorp** [comment] 2018-06-08 00:58
Hi, I'm unable to repro this on my end, with an enlistment of the 0.7.1 version. 

That error usually stems from unrecognized labels or syntax issues. Your syntax looks fine.  
Could this be a dupe of #621? There's a fix for it, but it looks like it hasn't been released.

**Comment by StephenWeatherford** [comment] 2018-06-08 19:45
Verfied that it is fixed in 0.8.0.

**Closed by StephenWeatherford** 2018-06-08 19:45 UTC

**Comment by PrashanthCorp** [comment] 2018-07-06 19:21
Hi @dianasotirova, the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.
