### ISSUE TITLE
Unable to update Mongo records.

### ISSUE THREAD

**Issue by Goddak** [Microsoft/vscode-cosmosdb#664] opened 2018-06-07 09:28 UTC
Repro steps:
- Connect to Mongo DB
- Select a databse and find a record to ammend
- Update a string (I added a word to a name just to test the extension)
- Receive an popup asking if you want to upload/always upload
- Select upload (For now, plus it's a chance to sanity check changes)
- Receive the error
![image](https://user-images.githubusercontent.com/12832288/41090921-49f09c42-6a3d-11e8-96c1-ff5930224a74.png)

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: Error
Error Message: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

Version: 0.7.1
OS: linux
![image](https://user-images.githubusercontent.com/12832288/41090983-6fa0ab44-6a3d-11e8-8175-3d510ac64a54.png)

**Comment by Goddak** [comment] 2018-06-07 09:30
Dupe of https://github.com/Microsoft/vscode-cosmosdb/issues/663
- Though I feel this is better structured.

**Comment by PrashanthCorp** [comment] 2018-06-08 01:45
Looks like a dupe of #534.

**Comment by PrashanthCorp** [comment] 2018-06-08 22:37
Close via PR

**Closed by PrashanthCorp** 2018-06-08 22:37 UTC
Labels: bug

**Comment by PrashanthCorp** [comment] 2018-07-06 19:21
Hi @Goddak , the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.

**Comment by Goddak** [comment] 2018-07-10 12:19
@PrashanthCorp - It's been working a joy, thank you :D
