### ISSUE TITLE
An unexpected error occured while deleting a PostgreSQL server database

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1456] opened 2020-05-09 10:01 UTC
**OS:** Win10
**Build Version:**[ 20200508.8](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19001&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Drill down a PostgreSQL account.
2. Right click the database --> Delete Database...

**Expect:**
Delete the database successfully.

**Actual:**
Fail to delete the database.
![image](https://user-images.githubusercontent.com/57662131/81467216-d7235780-9209-11ea-857b-4d8f592e30a4.png)

**Comment by wwlorey** [comment] 2020-05-20 20:34
I'm not able to reproduce this. It may have been a temporary Azure outage. @neelip can you repro?

**Comment by v-ruizh** [comment] 2020-05-27 02:05
This issue does not reproduce on the new build 20200522.22, close it.

**Closed by v-ruizh** 2020-05-27 02:05 UTC
Labels: AT-CTI, needs more info, postgres
