### ISSUE TITLE
Getting error when doing Exercise on doc

### ISSUE THREAD

**Issue by kamleshkumar-gep** [microsoft/vscode-cosmosdb#1478] opened 2020-05-20 10:54 UTC
Repro steps:

1.
2.

Action: cosmosDB.createAccount
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: 8a7fbe89-7f27-4f32-82a9-dc265fc6be55, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Do...

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

**Comment by EricJizbaMSFT** [comment] 2020-05-21 19:57
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1472

**Closed by EricJizbaMSFT** 2020-05-21 19:57 UTC
