### ISSUE TITLE
Group context menu commands

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#734] opened 2018-06-29 18:14 UTC
It looks like [App service](https://github.com/Microsoft/vscode-azureappservice/pull/489), [Storage](https://github.com/Microsoft/vscode-azurestorage/pull/183), and [Functions](https://github.com/Microsoft/vscode-azurefunctions/pull/427) have it. 

Do we consider this high enough priority w.r.t the cosmosDB extension?

**Comment by EricJizbaMSFT** [comment] 2018-06-29 18:23
Closing as dupe of https://github.com/Microsoft/vscode-cosmosdb/issues/98

**Closed by EricJizbaMSFT** 2018-06-29 18:23 UTC
Labels: duplicate
