### ISSUE TITLE
Trying to query mongodb with a partial match not working

### ISSUE THREAD

**Issue by ImreC** [Microsoft/vscode-cosmosdb#786] opened 2018-08-07 14:03 UTC
Repro steps:
Query I am using in my scrapbook:
db.collection.find({name: /test/})
This works perfectly from Mongo Compass or Robo3T

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 37: 'missing '(' at ''('''. Please check syntax.

Version: 0.8.0
OS: win32

**Comment by StephenWeatherford** [comment] 2018-08-07 18:28
@PrashanthCorp Perfect testcase for your regexp work.

**Comment by PrashanthCorp** [comment] 2018-08-07 18:42
Thanks for pointing this out. Marking as dupe of #667 .

**Comment by ImreC** [comment] 2018-08-08 06:56
The work around in #667 is totally fine for me, but good to read it's on the map.

**Comment by PrashanthCorp** [comment] 2018-09-28 21:28
Closing as fixed

**Closed by PrashanthCorp** 2018-09-28 21:28 UTC
Labels: P1, feature
