### ISSUE TITLE
Error trying to upload document when you add a value for the partition key

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#577] opened 2018-04-30 23:14 UTC
1) Create a SQL collection with partition name = "name"
2) Create new document
3) Add a value for property name:
![image](https://user-images.githubusercontent.com/6913354/39454657-7db172fa-4c91-11e8-99e2-1b5f6aa87c75.png)
4) CTRL+S
5) Error: Resource Not Found

**Comment by StephenWeatherford** [comment] 2018-04-30 23:29
Same behavior in portal.

**Comment by PrashanthCorp** [comment] 2018-04-30 23:37
That's by design. The partition key value helps the storage engine know which partition to look into. Changing the value of the partition key is equivalent to providing a different path to look for. 

Closing this as bydesign. 

I think the ideal behavior you're looking for is at: https://github.com/Microsoft/vscode-cosmosdb/issues/358

**Closed by PrashanthCorp** 2018-04-30 23:37 UTC
Labels: bydesign
