### ISSUE TITLE
No response on running Gremlin queries on graph database(Cosmos DB)

### ISSUE THREAD

**Issue by ApoorvaMSRI** [microsoft/vscode-cosmosdb#1657] opened 2020-08-11 22:42 UTC
**Description**
After connecting to our Azure account, we can see list of databases etc.
But when we try to run the query and get all the nodes or edges and visualize them, we don’t see any results or not even any log/error messages.
However, modifications to the data in the graph is working well.
It would be very helpful if we could get a better understanding of why this problem is occurring and how to resolve it. :)
**Platform details:** 
OS : Win10
Version of VSCode : 1.47.3
Version of extension Azure Databases : v0.14.0
Version of extension Azure Cosmos DB Graph : v0.1.0
Version of extension Azure signin : v0.8.11

**Repro steps :**
Add above extensions
Sign in to azure account and connect to azure cosmos database resource
Open a  graph(having some data) and run gremlin queries (like g.V())
No response for both graph or Json tab (Attached ss)
![gitissue1](https://user-images.githubusercontent.com/69544846/89955662-28037b80-dc51-11ea-9fb9-263e6108285b.png)

**Comment by EricJizbaMSFT** [comment] 2020-08-20 22:23
Closing as dupe of https://github.com/microsoft/vscode-cosmosdbgraph/issues/6

**Closed by EricJizbaMSFT** 2020-08-20 22:23 UTC
