### ISSUE TITLE
Replace "DocumentDB" with "SQL"

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-cosmosdb#520] opened 2018-04-11 20:45 UTC
I have confirmation from the Cosmos DB team that this should absolutely be "SQL."

See also: https://docs.microsoft.com/en-us/azure/cosmos-db/faq

**Comment by StephenWeatherford** [comment] 2018-04-11 21:10
Should we do something like "SQL (DocumentDB)"?

**Comment by fiveisprime** [comment] 2018-04-11 22:10
Let's just go with "SQL" and we can link to the FAQ in the changelog for clarification. This will be consistent with the portal.

**Comment by StephenWeatherford** [comment] 2018-04-12 00:09
Dupe of #415

**Closed by StephenWeatherford** 2018-04-12 00:09 UTC
