### ISSUE TITLE
Regular expressions not executing in Mongo scrapbook

### ISSUE THREAD

**Issue by mmartel75** [microsoft/vscode-cosmosdb#1634] opened 2020-07-23 07:21 UTC
Steps to reproduce:
1. Connect to a Mongo DB server with a Mongo scrapbook
2. Try to run a $regex query (e.g., {"name": {$regex: "Tur.*"}} )
3. Observe there are zero results returned (no errors)

Expected behavior:
To see non-zero results returned. If I run this identical query {"name": {$regex: "Tur.*"}} using Python (pymongo) or a MongoDB shell, I see 2 results returned (out of my 688 documents). But when running the exact same regex query through a Mongo Scrapbook in VS Code, I see zero results.

**Comment by nturinski** [comment] 2020-07-23 22:23
Duplicate of #1629

**Closed by nturinski** 2020-07-23 22:23 UTC
