### ISSUE TITLE
The database disappears under the MongoDB account after restarting vs code

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-cosmosdb#2047] opened 2022-07-05 08:58 UTC
**OS:** Win 10
**Build Version:** 20220704.1

**Repro Steps:**
1. Right click a MongoDB account -> Create a database.
2. Restart vs code -> Expand the MongoDB account.
3. Check whether the database still exists after restarting.

**Expect:**
The database still exists after restarting.
![image](https://user-images.githubusercontent.com/107091828/177288048-67524b00-99cd-4be4-b07e-2c729e7d32c9.png)

**Actual:**
The database disappears after restarting.
![image](https://user-images.githubusercontent.com/107091828/177288088-040c8821-5674-402c-810b-0a25e756ef62.png)

**More Info:**
This issue can be fixed after refreshing the MongoDB account.

**Comment by nturinski** [comment] 2022-09-15 22:15
I can only get this to reproduce if I cancel out of this step:

![image](https://user-images.githubusercontent.com/5290572/190518092-63e4a147-a9c2-4978-a959-bbfb00d2c9f8.png)

After restarting and refreshing, it doesn't reappear however.  Are you canceling out of the `Collection Name` step?

**Comment by v-chenzha** [comment] 2022-09-26 07:48
@nturinski Verified on the latest build 20220925.1, this issue still reproduces for now.

The Database is normally created with collection name. I didn't cancel the collection name.

**Comment by sevoku** [comment] 2024-11-13 23:47
I can't reproduce this. It might probably only happen if creation takes longer than restarting. Please share if there is something in the output of the Output window. Closing for now.

**Closed by sevoku** 2024-11-13 23:47 UTC
Labels: AT-CTI
