### ISSUE TITLE
Unable to create Azure cosmos db account

### ISSUE THREAD

**Issue by vedantshinde** [microsoft/vscode-cosmosdb#1514] opened 2020-05-25 07:28 UTC
Repro steps:

1. Select the "Create Account" button in the Azure Cosmos DB section.
2. Complete the process.

Action: cosmosDB.createAccount
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: 0d720688-df7a-41c6-bbe8-e1d881118849, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0".

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
PollingState.getCloudError extension.bundle.js:614:115518
extension.bundle.js:529:61135extension.bundle.js:529:61135
extension.bundle.js:245:24944extension.bundle.js:245:24944
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-06-11 22:50
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1510

**Closed by EricJizbaMSFT** 2020-06-11 22:50 UTC
