### ISSUE TITLE
[Suggestion]Display a more clear error message after attaching emulator without emulator installed

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#807] opened 2018-09-04 07:41 UTC
Repro Steps:
1. Make sure the Azure Cosmos DB Emulator is not installed.
2. Right click 'Attached Database Accounts' node -> Select 'Attach Emulator' ->Select one Database Account API.
3. Check the result.

Actual:
Pop up an error 'failed to connect to server...'.

Suggestion:
Display a clearer error message and add a link for the customers to install the Azure Cosmos DB Emulator.
![add](https://user-images.githubusercontent.com/34729092/45015454-4c8c5d00-b011-11e8-9be7-31d3aaf8ef00.PNG)

**Comment by PrashanthCorp** [comment] 2019-02-28 00:00
Dupe of #706.

**Closed by PrashanthCorp** 2019-02-28 00:00 UTC
Labels: AT-CTI, P2

**Comment by v-dantch** [comment] 2019-02-28 06:22
Got it. Thanks for your sharing and update.
