### ISSUE TITLE
The input box is not focused when creating a database account

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-cosmosdb#2072] opened 2022-10-20 07:42 UTC
**OS:** Win10
**Build Version:** 20221019.1
**Visual Studio Code Insiders Version**: 1.73.0

**Repro Steps:**

1. Install Azure Databases extension.
2. Right click "Azure Cosmos DB" -> Click "Create Server".
3. Check whether only the input box is focused.

**Expect:**
Only the input box is focused.
![image](https://user-images.githubusercontent.com/107091828/196884313-4e562f3d-9df6-44c0-b5d3-b0686e2a7fed.png)

**Actual:**
The input box is not focused.
![image](https://user-images.githubusercontent.com/107091828/196884071-bd4a2e7a-358c-4cb3-bfe4-6cbbf6f37d7a.png)

**Comment by alexweininger** [comment] 2022-12-07 23:44
Tracking upstream VS Code issue https://github.com/microsoft/vscode/issues/163753

**Comment by sevoku** [comment] 2024-11-13 23:43
This has been fixed in VSCode, I can't reproduce this anymore.

**Closed by sevoku** 2024-11-13 23:43 UTC
Labels: bug, AT-CTI, tracking, upstream
