### ISSUE TITLE
unable to attach database

### ISSUE THREAD

**Issue by Harshitb1** [Microsoft/vscode-cosmosdb#864] opened 2018-10-12 19:47 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment] 2018-10-12 21:09
Looks like a duplicate of #662. Please let us know if that doesn't work.

**Comment by StephenWeatherford** [comment] 2018-10-12 22:42
@Harshitb1 You need to have started your local database before you can connect to it. Please follow the instructions @PrashanthCorp points to above and let us know if there are other issues, thanks.

**Closed by StephenWeatherford** 2018-10-12 22:42 UTC
