### ISSUE TITLE
Connecting to local emulator graph

### ISSUE THREAD

**Issue by javaadpatel** [microsoft/vscode-cosmosdb#1175] opened 2019-08-29 07:38 UTC
Hi,

I've setup the local graph emulator as per: https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#gremlin-api . Is it possible to connect to the local cosmosdb emulator graph endpoint to visualize the graph? 
It seems that the problem is that the local emulator doesn't support SSL so I get this error:
![image](https://user-images.githubusercontent.com/22832462/63920296-cc8cad80-ca40-11e9-93be-6198fa93b7dc.png)

**Comment by PrashanthCorp** [comment] 2019-09-11 22:59
Related to #1164

**Comment by nturinski** [comment] 2020-01-23 23:30
Closing as dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1248

**Closed by nturinski** 2020-01-23 23:30 UTC
