### ISSUE TITLE
Support connections to local TinkerPop Server instance

### ISSUE THREAD

**Issue by nathanwinder** [microsoft/vscode-cosmosdb#1164] opened 2019-08-18 15:42 UTC
The Cosmos emulator does not support graph databases so I'd like the ability to connect to a local TinkerPop Server instance.

**Comment by PrashanthCorp** [comment] 2019-08-19 19:05
Hi @nathanwinder , thanks for filing the issue! Is there any blocker on attaching your local Tinkerpop instance using the attach database command?

**Comment by nathanwinder** [comment] 2019-08-20 01:07
Sorry, didn't realize that could be used to connect to a non-cosmos DB.
What is the connection string format when connecting with local TinkerPop,
the hint is 'AccountEndpoint=...;AccountKey=...' so I assumed to was Cosmos
only

Thanks,
Nathan

**Comment by nathanwinder** [comment] 2019-08-20 13:43
I took a closer look at this. First the connection string must be in the format "AccountEndpoint=...;AccountKey=...' and the account endpoint must start with "https". That means 1) I'd have to run the tinker pop server with ssl enabled (setup key store etc) and 2) I'm not sure what I would supply for AccountKey.

**Comment by StephenWeatherford** [comment] 2019-08-22 22:06
Yeah, currently we're expecting Cosmos graph, although that's probably not a technical requirement. Interested in making changes to allow this?  I'm not sure when we'd be able to get to it ourselves.

**Comment by nturinski** [comment] 2020-01-23 23:30
Closing as dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1248

**Closed by nturinski** 2020-01-23 23:30 UTC
Labels: graph
