### ISSUE TITLE
Fail to delete a PostgreSQL server

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2007] opened 2022-05-16 08:35 UTC
**OS:** Win10
**Build Version:** 20220514.1

**Repro Steps:**
1. Right click a PostgreSQL server -> Click "Delete...".
2. .Check whether succeeds to delete a PostgreSQL server.

**Expect:**
Succeed to delete a PostgreSQL server.

**Actual:**
Fail to delete a PostgreSQL server.
![image](https://user-images.githubusercontent.com/57662131/168550993-be28c653-583f-461d-9789-e60acdbfb292.png)

**Comment by nturinski** [comment] 2022-05-16 23:21
This seems to be an issue with keytar.  The server still actually deletes successfully, but the password isn't being correctly deleted.  We could suppress the JSON parsing error for now.

**Comment by alexweininger** [comment] 2022-05-17 00:50
> We could suppress the JSON parsing error for now.

We should consult the rest of the team, but that sounds good to me. It might be nice to have a better understanding of the keytar issues though.

**Comment by nturinski** [comment] 2022-05-17 06:55
Related to https://github.com/microsoft/vscode-azurestorage/issues/1045 (since it's all keytar related)

**Comment by nturinski** [comment] 2022-08-18 22:58
Here is the fix for [Storage](https://github.com/microsoft/vscode-azurestorage/commit/9018b02564f6e61df2ec9d2ec10e7e3c379fc1d9)

**Comment by JasonYeMSFT** [comment] 2023-09-20 18:44
I believe this has been fixed. The extension has replaced keytar with vscode secret storage module.

**Comment by v-xinda** [comment] 2023-09-21 06:02
@JasonYeMSFT This issue also reproduces on the build 20230920.5.
An error occurs after deleting a PostgreSQL account. 
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/91a2fd81-8165-4491-869d-3a580ba0cb17)
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/720f017b-4f9e-45f1-ac2b-8aeedda04358)
The PostgreSQL account disappears after refreshing the Resource view.

**Comment by JasonYeMSFT** [comment] 2023-09-25 17:13
I misunderstand the status of the migration to secretStorage. The work is done but the latest release is still using it. We don't have any migration code in place so it would be a little bizarre for people who just upgraded to 0.20.0. I'll make sure at least it doesn't have any consequences and won't block users.

**Comment by JasonYeMSFT** [comment] 2023-09-25 18:47
I tried but I am not able to reproduce this issue. From the code point of view, this could happen if there are is a concurrently execution that attempts to read that node which has been partially destroyed. I will close this issue for now given that the consequence is small and the deletion does complete.

**Closed by JasonYeMSFT** 2023-09-25 18:47 UTC
Labels: bug, AT-CTI, investigate
