### ISSUE TITLE
No name validation when creating Mongo/SQL collections

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-cosmosdb#1311] opened 2020-01-23 00:34 UTC
Repro steps:

1. Have a collection "col"
2. Try to create another collection named "col"
3. Allows you, but throws an error

Action: cosmosDB.createDocDBCollection
Error type: Conflict
Error Message: Resource with specified id, name, or unique index already exists.

Version: 0.12.1-alpha
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.42.0-insider
Language: en

**Comment by EricJizbaMSFT** [comment] 2020-01-28 19:02
Closing as dupe of https://github.com/microsoft/vscode-cosmosdb/issues/328

**Closed by EricJizbaMSFT** 2020-01-28 19:02 UTC
