### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rassouldev** [Microsoft/vscode-cosmosdb#682] opened 2018-06-14 11:53 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.7.2
OS: darwin

**Comment by PrashanthCorp** [comment] 2018-06-14 19:07
I'm closing this as a dupe of #662

**Closed by PrashanthCorp** 2018-06-14 19:07 UTC

**Comment by StephenWeatherford** [comment] 2018-06-14 19:27
@rassouldev It appears this is a common misunderstanding among customers, i.e. knowing that they need to have the local DB running if they want to connect to the default local port of 127.0.0.1.  Could you suggest what our extension do to better help someone avoid this problem?  Thx.

**Comment by PrashanthCorp** [comment] 2018-06-14 19:32
@rassouldev it would be great if you let us know if [this comment](https://github.com/Microsoft/vscode-cosmosdb/issues/662#issuecomment-395891819) would help solve your problem.

**Comment by rassouldev** [comment] 2018-06-18 10:31
Thanks @StephenWeatherford and @PrashanthCorp
