### ISSUE TITLE
Unable to create cosmosdb account in Norway east

### ISSUE THREAD

**Issue by FredrikEdenqvist** [microsoft/vscode-cosmosdb#1535] opened 2020-05-27 13:28 UTC
Repro steps:
I was following course: Build a Node.js app for Azure Cosmos DB in Visual Studio Code 
Step: Exercise - Create a Cosmos DB instance using Visual Studio Code
Bullit 10: I entered Norway east
After awhile this error comes and wanted to be reported.

**If you dont need this report, just close it.** Ill try with a different region.

Action: cosmosDB.createAccount
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: 2e514c7b-c8e2-4782-8e60-db20ae3771dd, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0".

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
PollingState.getCloudError extension.bundle.js:614:115518
extension.bundle.js:529:61135extension.bundle.js:529:61135
extension.bundle.js:245:24944extension.bundle.js:245:24944
s extension.bundle.js:245:40152
extension.bundle.js:529:60769extension.bundle.js:529:60769
```

</details>

**Comment by nturinski** [comment] 2020-06-04 18:59
Dupe of #1472

**Closed by nturinski** 2020-06-04 18:59 UTC
