### ISSUE TITLE
mongodb connection issue

### ISSUE THREAD

**Issue by pranav-sharma-au5** [microsoft/vscode-cosmosdb#1353] opened 2020-03-10 12:38 UTC
Repro steps:

1.
2.

Action: cosmosDB.connectMongoDB
Error type: Error
Error Message: Language client is not ready yet

Version: 0.12.1
OS: win32
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
LanguageClient.sendRequest vscode-languageclient/client.js:1615:19
MongoDBLanguageClient.<anonymous> extension.bundle.js:614:1081341
extension.bundle.js:614:1080477extension.bundle.js:614:1080477
n extension.bundle.js:614:1080222
MongoDBLanguageClient.connect extension.bundle.js:614:1081289
Object.<anonymous> extension.bundle.js:614:1078327
a extension.bundle.js:614:1074782
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-03-10 17:01
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1334

**Closed by EricJizbaMSFT** 2020-03-10 17:01 UTC
