### ISSUE TITLE
Load More, Not Working

### ISSUE THREAD

**Issue by ifmx** [microsoft/vscode-cosmosdb#2040] opened 2022-06-15 14:49 UTC
Does this occur consistently? 
Repro steps:

1. Load More, Not Working

Version: 0.19.1
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.68.0
Language: en

**Comment by alexweininger** [comment] 2022-08-18 22:07
Closing as duplicate of #2039

**Closed by alexweininger** 2022-08-18 22:07 UTC
