### ISSUE TITLE
Retryable writes are not supported when creating MongoDB database

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-cosmosdb#1296] opened 2020-01-17 22:09 UTC
Repro steps:

1. Create a new Cosmos DB instance with the Mongo API in Azure
2. Browse to it in VS Code, and attempt to create a new database and collection

The creation apparently succeeded, but an error notification was displayed:

Action: cosmosDB.createMongoDatabase
Error type: 2
Error Message: Retryable writes are not supported. Please disable retryable writes by specifying "retrywrites=false" in the connection string or an equivalent driver specific config.

Version: 0.12.0
OS: darwin
Product: Visual Studio Code - Insiders
Product Version: 1.42.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
Connection.<anonymous> mongodb/pool.js:466:61
Connection.emit events.js:203:13
processMessage mongodb/connection.js:364:10
TLSSocket.<anonymous> mongodb/connection.js:533:15
TLSSocket.emit events.js:203:13
addChunk _stream_readable.js:295:12
readableAddChunk _stream_readable.js:276:11
TLSSocket.Readable.push _stream_readable.js:210:10
TLSWrap.onStreamRead stream_base_commons.js:166:17
```

</details>

**Comment by connor4312** [comment] 2020-01-17 22:11
I consistently receive the same error whenever I try to right click and "Create Document" on the collection.

**Comment by pomberer** [comment] 2020-01-24 07:44
I am observing the same issue when connecting to cosmos mongo db wireprotocol version 3.6:

com.mongodb.MongoCommandException: Command failed with error 2 (BadValue): 'Retryable writes are not supported. Please disable retryable writes by specifying "retrywrites=false" in the connection string or an equivalent driver specific config.' on server xxx.mongo.cosmos.azure.com:10255. The full response is {"ok": 0.0, "errmsg": "Retryable writes are not supported. Please disable retryable writes by specifying \"retrywrites=false\" in the connection string or an equivalent driver specific config.", "code": 2, "codeName": "BadValue"}

**Comment by EricJizbaMSFT** [comment] 2020-03-09 16:48
Closing as duplicate of https://github.com/microsoft/vscode-cosmosdb/issues/1343

**Closed by EricJizbaMSFT** 2020-03-09 16:48 UTC

**Comment by sinal01** [comment] 2020-03-11 23:42
I don't see the solution/fix for the issue and 1296 is also closed. Can some one give a clear solution as setting retryWrites: false looks like did not work..

**Comment by raaedserag** [comment] 2020-04-19 09:19
I had the same issue and I solved it by setting 'retrywrites=false' at the connection string like this:
`mongodb://<username>:<password>@<host>:<port>/<db_name>?ssl=true&replicaSet=globaldb&retrywrites=false
`

**Comment by maheshsabnis** [comment] 2020-04-20 17:41
In My case still I am getting the same error 

"Retryable writes are not supported. Please disable retryable writes by specifying \"retrywrites=false\" in the connection string or an equivalent driver specific config.", 

I am using Mongoose driver to connect to MongoDB API in CosmosDB.

I am following steps in the following link
https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-mongoose

Not understanding where am I going wrong.

**Comment by maheshsabnis** [comment] 2020-04-20 17:52
Well I resolved it by modifying the the mongoose connection using following

mongoose.connect(connString, {
        useUnifiedTopology: true,
        useNewUrlParser: true,
        auth: {
            user: dbConfig.COSMOS_USER,
            password: dbConfig.COSMOS_PASSWORD
        }
    })
    .then(() => console.log('Connection to CosmosDB successful'))
    .catch((err) => console.error(err));
