### ISSUE TITLE
Fail to delete the function query with name contains the uppercase letter

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1806] opened 2021-01-26 09:44 UTC
**OS:** Windows
**Build Version:** 20210125.1

**Repro Steps:**
1. Create a PostgreSQL server.
2.  Create a function query with name "Test" to the server.
3. Delete the function query.
4. Check whether the function query is deleted successfully or not.

**Expect:**
The function query is deleted successfully.

**Actual:**
Fail to delete the function query with an error.
![image](https://user-images.githubusercontent.com/57662131/105828371-054a0100-5ffe-11eb-92c6-dbcb36365c11.png)

**More Info:**
1. This issue also reproduces for the stored procedures query.
2. The function query "Test" is deleted successfully after creating a function query with name "test".
3. Fail to delete the function query "test" after deleting the function query "Test".
![image](https://user-images.githubusercontent.com/57662131/105828380-09761e80-5ffe-11eb-960b-f1e2832405aa.png)

**Comment by neelip** [comment] 2021-01-28 22:02
I am unable to reproduce this error. When I created a function called "Test" and executed the query, the function was created with a name in all lowercase letters. The deletion of this new function was successfully when I tried on my end. 

Have you executed the query with `Execute Query` command? And was the execution successful?
You should see this response in Output if the execution was successful:
`Successfully executed "CREATE" query.`

**Comment by v-xinda** [comment] 2021-01-29 02:50
@neelip Hi, verified this issue on the latest build 20210128.1, it still reproduces. 
I execute the query with `Execute Query` command successfully, and the log `Successfully executed "CREATE" query.` shows in Output. Please get the more details from below.
![deletefunc](https://user-images.githubusercontent.com/57662131/106225006-3bb29680-621f-11eb-8fed-66bfbda8ef89.gif)

**Comment by neelip** [comment] 2021-02-01 21:25
You are right, I was looking at the latest extension release but not the build. This happening because of recent bug fixes. 
This should be fixed with the next release.

**Comment by v-xinda** [comment] 2021-03-17 08:17
This is issue also reproduces on Stored Procedures.
Get more details from below:
![delete](https://user-images.githubusercontent.com/57662131/111435650-ff3dea00-873b-11eb-8a34-0e6d1a7afb44.gif)

**Closed** 2021-04-09 08:40 UTC
Labels: AT-CTI, investigate, needs more info
