### ISSUE TITLE
There is no output log about "Successfully set up credentials... and Added firewall rule..."

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1541] opened 2020-05-28 09:38 UTC
**OS:** All
**Build Version:** 20200527.16

**Repro Steps:**
1. Create a PostgreSQL server with "Add firewall rule..." selected.
2. Check the output logs.

**Expect:**
There are output logs about "Successfully set up credentials... and Added firewall rule...".

**Actual:**
There is no output log about "Successfully set up credentials... and Added firewall rule...".
![image](https://user-images.githubusercontent.com/45614674/83125278-e9f2c300-a109-11ea-9c4f-10d536f7df5a.png)

**Comment by neelip** [comment] 2020-05-28 17:35
Given setting up credentials and adding firewall rule are part of the create process, is one "Successfully created..." message enough in this case?

**Comment by EricJizbaMSFT** [comment] 2020-05-28 17:47
I kind of feel like every in-progress message (aka "Creating...") should have a matching completion message (aka "Successfully created."). It's almost easier to follow a consistent pattern like that instead of picking and choosing which ones do or don't need the completion message. In this case, just because the server was created, doesn't mean the firewall rule was successfully added.

Do I think it's high priority, though? Definitely not

**Comment by jinglouMSFT** [comment] 2020-05-28 18:23
I agree with Eric in terms of "Creating" and "Created" pairs.  
Only if we need to rebuild 0.13.0 and it's low risk to fix, I think this one can wait until 0.14.0.

**Comment by v-mengwe** [comment] 2020-09-15 06:24
Verified on the latest build 20200914.4, this issue doesn't reproduce, so close it.

**Closed by v-mengwe** 2020-09-15 06:24 UTC
Labels: AT-CTI, postgres
