### ISSUE TITLE
Hi all At selecting location, i get an error. Anyone care to advise.

### ISSUE THREAD

**Issue by ericytex** [microsoft/vscode-cosmosdb#1476] opened 2020-05-20 05:23 UTC
Repro steps:

1.Open VS code
2.Add Azure cosmos db extention
3.sign into azure
4.using the concierge subscription, create a cosmos db account
5 select location eg; south Africa North....

Action: cosmosDB.createAccount
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: b6f759e1-ade9-4943-86d7-a2eee6d9a92e, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0".

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
PollingState.getCloudError extension.bundle.js:614:115518
extension.bundle.js:529:61135extension.bundle.js:529:61135
extension.bundle.js:245:24944extension.bundle.js:245:24944
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-05-21 19:56
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1472

**Closed by EricJizbaMSFT** 2020-05-21 19:56 UTC
