### ISSUE TITLE
Can not connect to mongodb replica secondary

### ISSUE THREAD

**Issue by tonylsw** [microsoft/vscode-cosmosdb#1270] opened 2019-12-27 02:27 UTC
I'm trying to connect to one of the secondary hosts in a replica set (hosted on AWS), the connection used is:
  mongodb://user:password@host:port

This work fine when the host is a primary, if it is a secondary, the connection is established without error,  but I got "Error: not master and slaveOk=false" when trying to access the db.

I'm aware I can connect to a mongo replica set with "replicaSet=rs_name" option, but I'd like to connect to  a host for read-only operations.

**Comment by wwlorey** [comment] 2020-06-05 21:41
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/565

**Closed by wwlorey** 2020-06-05 21:41 UTC
Labels: investigate
