### ISSUE TITLE
Unable to Query Collection with a Period in the Collection Name

### ISSUE THREAD

**Issue by dprice** [Microsoft/vscode-cosmosdb#684] opened 2018-06-14 20:16 UTC
**Repro steps:**

1. Create a new database "MyTest" on 127.0.01:27017
2. Create a new collection "My.Collection"
3. Create a new empty document (only contains ObjectId)
4. Create a new MongoDB scrapbook
5. Copy the following queries into the scrapbook:
- Running this query:
```javascript
db.getCollection('My.Collection').find()
```
Results in a new window with "MyTest.My.Collection" displayed

- Running this query:
```javascript
db.My.Collection.find()
```
Results in a VSCode Azure Cosmos DB Extension error "Error near line 0, column 16, text '.'. Please check syntax."

- Running this query:
```javascript
db["My.Collection"].find()
```
Results in a VSCode Azure Cosmos DB Extension error "Error near line 0, column 16, text '.'. Please check syntax."

Pasting all of the above queries into Robo 3T v1.2.1 all succeed and display the empty document:
```json
{
    "_id" : ObjectId("5b22c66eaf6f2f58247a2f2b"),
}
```

**Reproducing the above steps with a collection with NO period in the name**

1. Create a new database "MyTest" on 127.0.01:27017
2. Create a new collection "MyCollection"
3. Create a new empty document (only contains ObjectId)
4. Create a new MongoDB scrapbook
5. Copy the following queries into the scrapbook:
- Running this query:
```javascript
db.getCollection('MyCollection').find()
```
Results in a new window with "MyTest.MyCollection" displayed

- Running this query:
```javascript
db.MyCollection.find()
```
Results in correctly displaying the collection data:
```json
[
  {
    "_id": {
      "$oid": "5b22ca71af6f2f58247a2f2d"
    }
  }
]
```

- Running this query:
```javascript
db["MyCollection"].find()
```
Never returns any result, error, or anything.

Pasting all of the above queries into Robo 3T v1.2.1 all succeed and display the empty document:
```json
{
    "_id" : ObjectId("5b22ca71af6f2f58247a2f2d")
}
```

So how do I query my collection with a period in the name? Why does Robo 3T run all queries successfully but Cosmos DB does not?

~~~

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 16, text '.'. Please check syntax.

Version: 0.7.2
OS: win32
MongoDB shell version v3.4.7

**Comment by PrashanthCorp** [comment] 2018-06-14 23:49
Hi Derek, 

Thanks for your patience in taking the time to write such a detailed description and repro of the bug. 

> So how do I query my collection with a period in the name? Why does Robo 3T run all queries successfully but Cosmos DB does not?

Unfortunately, we currently cannot. We are aware of this limitation, and we're working towards fixing it. See #666 for a prior discussion. Thanks for the bug report, it helps us understand better what feature requests are higher priority. We didn't realize how popular it was to have periods in the collection names. :) 


This looks like a dupe of #666 - am I understanding the issue correctly?

**Comment by dprice** [comment] 2018-06-15 13:41
Yeah - looks like a duplicate. When the error happened in VSCode I hit the Report Issue button and just posted above. If I had known periods in collection names were such an issue, I would have never put one in there!

**Comment by PrashanthCorp** [comment] 2018-06-15 18:18
Thanks for the feedback . :) 

If you're interested, [this](https://github.com/Microsoft/vscode-cosmosdb/blob/f3641d4a88ebe8fe06120a9d2531e9e75e2e5633/grammar/mongo.g4#L22) is where we make the assumption of how a command's syntax is structured. 

We shall close this and mark it as a dupe of #666 - that would help us track it better.  Would that be fine?

**Comment by dprice** [comment] 2018-06-15 19:10
I'm okay with you closing this as a duplicate but I don't think it's unreasonable for any query that runs in Robo 3T to run in your VSCode extension. Your editing experience is far better although the presentation of data is far better in Robo 3T.

**Comment by StephenWeatherford** [comment] 2018-06-15 20:21
Thanks.  We definitely do want to fix this and are interested when things don't behave the same way.  It's not our goal to make *everything* work the same way, but definitely all the common scenarios should, so please continue to provide feedback.

**Closed by StephenWeatherford** 2018-06-15 20:21 UTC
