### ISSUE TITLE
resource group does not show

### ISSUE THREAD

**Issue by nils456** [microsoft/vscode-cosmosdb#1803] opened 2021-01-25 15:17 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureDatabases.createServer
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.DocumentDB'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 0.15.1
OS: win32
OS Release: 6.1.7601
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:56:970
extension.bundle.js:260:2896extension.bundle.js:260:2896
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nils456** [comment] 2021-01-25 15:23
Got over the MissingSubscriptionRegistration but when i go ahead and click on the "+" sign as given in the document, I don't get to select the resource group. I am forced to create a resource group and then it says you cannot create or link a resource group to this namespace .

**Comment by nturinski** [comment] 2021-01-27 19:44
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1795.

You should be able to follow the steps here https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types

**Closed by nturinski** 2021-01-27 19:44 UTC
