### ISSUE TITLE
We should capture the error from #662 and display a more useful message

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-cosmosdb#698] opened 2018-06-20 01:14 UTC
#662

**Comment by StephenWeatherford** [comment] 2018-06-25 22:06
Changing so that we only default to the local port if we can actually connect to it (i.e. it's currently running).

**Comment by StephenWeatherford** [comment] 2019-03-06 23:21
We're still getting people reporting this error, so we need to actually do the work to catch it and improve the error message.

**Comment by EricJizbaMSFT** [comment] 2020-02-06 23:28
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/866

**Closed by EricJizbaMSFT** 2020-02-06 23:28 UTC
Labels: P1
