### ISSUE TITLE
Refresh in "AZURE COSMOS DB" toolbar doesn't work for "Attach Database Accounts"

### ISSUE THREAD

**Issue by v-sezhan** [Microsoft/vscode-cosmosdb#312] opened 2017-12-27 09:53 UTC
Repro Steps:
1. Attach a Cosmos DB account which has database under it.
2. Delete this database from the account under the subscription.
3. Click "Refresh" icon in "AZURE COSMOS DB" toolbar.
4. Check if this database exists under "Attached Database Accounts".

Expect:
The deleted database also removes from "Attached Database Accounts".

Actual:
The deleted database also exists under "Attached Database Accounts". Refresh in "AZURE COSMOS DB" doesn't work. See the attached compare.png.
![compare](https://user-images.githubusercontent.com/27722878/34377653-ea58cf5a-eb2c-11e7-9375-4fc663e2d7cc.png)

More info:
The database removes after right-clicking the refresh from "Attached Database Accounts".

**Comment by EricJizbaMSFT** [comment] 2018-01-02 17:52
This is expected behavior. There's no internal mapping between attached accounts and subscription accounts.

Closing this since it has an easy workaround (hit refresh) and the user is unlikely to be using both the attached account and the subscription account at the same time.

**Closed by EricJizbaMSFT** 2018-01-02 17:52 UTC
