### ISSUE TITLE
Language client is not ready yet

### ISSUE THREAD

**Issue by sayantan-das-bchu** [microsoft/vscode-cosmosdb#1334] opened 2020-02-24 11:59 UTC
Repro steps:

1.
2.

Action: cosmosDB.connectMongoDB
Error type: Error
Error Message: Language client is not ready yet

Version: 0.12.1
OS: linux
Product: Visual Studio Code - Insiders
Product Version: 1.43.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
LanguageClient.sendRequest vscode-languageclient/client.js:1615:19
MongoDBLanguageClient.<anonymous> extension.bundle.js:614:1081341
extension.bundle.js:614:1080477
n extension.bundle.js:614:1080222
MongoDBLanguageClient.connect extension.bundle.js:614:1081289
Object.<anonymous> extension.bundle.js:614:1078327
a extension.bundle.js:614:1074782
```

</details>

**Comment by nturinski** [comment] 2020-02-24 18:33
Hi @sayantan-das-bchu 

Thanks for reporting.  I've been experiencing the same issue in Insiders.  Please use [VS Code Stable](https://code.visualstudio.com/) if this is blocking you, it seems like it's working no problems on there 😃

**Comment by dbaeumer** [comment] 2020-03-09 09:01
@nturinski since you can reproduce this can you please provider me with steps on how to do so.

This is not a problem of VS Code itself. It is either a problem of the 'vscode-languageclient' libraries managed here https://github.com/Microsoft/vscode-languageserver-node or an issue with your extension itself.

One situation that can happen is that the server crashes and is restarted which requires the onReady() to be rechecked. 

And you are using pretty outdated version of the libraries:

```
        "vscode-languageclient": "^4.4.0",
        "vscode-languageserver": "^4.4.0",
```

The onRady handling has majorly changed in the 6.x version to address bugs around reconnects. Are you experiencing the same issue with the 6.x versions ?

**Comment by EricJizbaMSFT** [comment] 2020-03-09 21:15
> since you can reproduce this can you please provider me with steps on how to do so.

All I have to do is install the Cosmos DB extension on VS Code insiders and activate the extension somehow (i.e. open the Cosmos DB view in the azure window) and the error happens.

We assumed it was related to VS Code itself because it repros consistently for us on Insiders and never on stable. Does the version of VS Code affect the version of the `vscode-language*` modules that are supported? We inherited most of this code and haven't touched it in a while. I can look into upgrading to 6.x, but it would take a bit of time to get ramped up and verify

**Comment by dbaeumer** [comment] 2020-03-10 08:47
I debugged it and the problematic code is when you start the language client here: https://github.com/microsoft/vscode-cosmosdb/blob/master/src/mongo/languageClient.ts#L24 which actually fails and then results in the followup errors. The initial fail is actually shown in the output channel of the server:

![capture](https://user-images.githubusercontent.com/1931590/76294944-12f67b00-62b4-11ea-8838-9152f493f0a0.png)

According to the NodeJS documentation an exit code of 9 indicates wrong or invalid arguments.

Couple of things:

- the `--debug` option is since a long time deprecated and since VS Code moved to a new Electron version I guess it is not supported anymore.
- never pass any debug options when in run mode. You basically always started the server in debug mode. If you would only do this when you actually run in debug the extension would still have worked when installed from the marketplace.

The correct code looks like this.

```ts
        const debugOptions = { execArgv: ['--nolazy', '--inspect=6005'] };

        // If the extension is launch in debug mode the debug server options are use
        // Otherwise the run options are used
        const serverOptions: ServerOptions = {
            run: { module: serverModule, transport: TransportKind.ipc },
            debug: { module: serverModule, transport: TransportKind.ipc, options: debugOptions }
        };
```

**Comment by EricJizbaMSFT** [comment] 2020-03-10 17:50
@dbaeumer very helpful, thanks!

I've filed a separate issue to update the language libraries: https://github.com/microsoft/vscode-cosmosdb/issues/1357

**Comment by aymericbouzy** [comment] 2020-03-11 08:08
I'm also having this issue, if I can be helpful by sharing my config or other, please reach out.

**Comment by EricJizbaMSFT** [comment] 2020-03-11 17:09
Hey all - we've shipped a fix for this. Please make sure you're on at least v0.12.2 of the Cosmos DB extension

**Closed by EricJizbaMSFT** 2020-03-11 17:09 UTC
Labels: P0, bug

**Comment by aymericbouzy** [comment] 2020-03-12 11:25
Thank you so much 🙏
