### ISSUE TITLE
An error occurs after expanding the database of the Mongo DB/SQL account in the Azure China account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2225] opened 2024-01-05 03:54 UTC
**OS:** Win10
**Build Version:** 20240104.1
**Regression:** Not a regression

**Repro Steps:**
1. Sign in with Azure China account.
2. Create a Mongo DB account -> Expand the Mongo DB account -> Create a new database.
3. Expand the above database.
4. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/5f386963-e413-46c2-854d-72e5f3328d4d)

**More Info:**

1. This issue doesn't reproduce after signing in Azure account.
2. This issue also reproduces for the SQL account.

**Comment by JasonYeMSFT** [comment] 2024-01-16 18:57
I need to find out if the extension actually works at all with Azure China.

**Comment by JasonYeMSFT** [comment] 2024-02-27 21:47
The extension should work with Azure China. I cannot reproduce this error. I will try to add more logging around the node production to hopefully get more details the next time you reproduce it.

**Comment by sevoku** [comment] 2024-11-13 22:39
Closing since this doesn't seem to be an issue with the extension itself.

**Closed by sevoku** 2024-11-13 22:39 UTC
Labels: AT-CTI
