### ISSUE TITLE
There is no validation when entering the database name with "@" or "#" for MongoDB account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1687] opened 2020-09-08 10:10 UTC
**OS:** All
**Build Version:** 20200905.5

**Repro steps:**

1. Right click a MongoDB account --> Select "Create Database..." --> Enter the database name with "@" or "#" --> Enter the collection name.
2. Check the result.

**Expect:**
There is a validation when entering the database name with "@" or "#".

**Actual:**

1. There is an error "unescaped slash in userinfo section" when entering the database name with "@" and the database "@" displays in the tree view.
 ![image](https://user-images.githubusercontent.com/62053665/92460961-3797c500-f1fb-11ea-8261-a0d1632f4dfd.png)
3. There is no error when entering the database name with "#" and keep loading when expanding it.
 ![image](https://user-images.githubusercontent.com/62053665/92461407-d7555300-f1fb-11ea-9e90-ba1e4e16b48c.png)
5. The database name "#" or "@" will disappear from the tree view after refreshing.
 ![image](https://user-images.githubusercontent.com/62053665/92461291-b12fb300-f1fb-11ea-9c34-19c125db9689.png)

Action: cosmosDB.createMongoDatabase
Error type: MongoParseError
Error Message: Unescaped slash in userinfo section

Version: 0.14.1-alpha
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
parseConnectionString mongodb/uri_parser.js:584:21
connect mongodb/connect.js:272:3
mongo_client.js:215:5mongodb/mongo_client.js:215:5
maybePromise mongodb/utils.js:719:3
MongoClient.connect mongodb/mongo_client.js:211:10
Function.MongoClient.connect mongodb/mongo_client.js:421:22
Object.<anonymous> extension.bundle.js:121:18594
extension.bundle.js:121:18262extension.bundle.js:121:18262
i extension.bundle.js:121:17948
Object.connectToMongoClient extension.bundle.js:121:18411
MongoDatabaseTreeItem.<anonymous> extension.bundle.js:173:45962
extension.bundle.js:173:44278extension.bundle.js:173:44278
i extension.bundle.js:173:43964
MongoDatabaseTreeItem.connectToDb extension.bundle.js:173:45913
MongoDatabaseTreeItem.<anonymous> extension.bundle.js:173:46808
extension.bundle.js:173:44278extension.bundle.js:173:44278
i extension.bundle.js:173:43964
MongoDatabaseTreeItem.createCollection extension.bundle.js:173:46755
MongoDatabaseTreeItem.<anonymous> extension.bundle.js:173:45501
fulfilled extension.bundle.js:173:44032
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by neelip** [comment] 2021-02-04 21:03
The issue "unescaped slash in userinfo section" should be fixed with next release. 

I am unable to reproduce the 3rd issue of disappearing databases in the tree view. The only time databases are disappearing after refresh is when the Collection name is not entered yet. If both the Database name and and Collection name are entered during the creation process then this error doesn't occur. 

Is it possible that you refreshed before entering the Collection name?

**Comment by neelip** [comment] 2021-02-04 21:18
"#" is not an allowed character in a database name for a Cosmosdb mongo resource. It is a bug which will be fixed with next release.

**Closed** 2021-02-12 20:30 UTC
Labels: AT-CTI, mongo
