### ISSUE TITLE
MongoDB Collections with dots throw errors

### ISSUE THREAD

**Issue by RayJin2000** [Microsoft/vscode-cosmosdb#710] opened 2018-06-25 13:56 UTC
Repro steps:
go to the local database and try to findOne entry of the collection oplog.rs
db.oplog.rs.findOne()

Action: cosmosDB.executeAllMongoCommands
Error type: Error
Error Message: Error near line 0, column 11, text '.'. Please check syntax.

Version: 0.7.2
OS: win32

**Comment by PrashanthCorp** [comment] 2018-06-25 17:48
It looks like the issue stems from having a collection name with a `.`o in its name. Is that correct? 

We're tracking that issue in #666. Let us know if that's the root cause of your problem.

**Comment by StephenWeatherford** [comment] 2018-06-27 22:30
I'm closing as a dup of #666.  If you feel this is not correct, feel free to reopen.  Thanks for reporting.

**Closed by StephenWeatherford** 2018-06-27 22:30 UTC

**Comment by PrashanthCorp** [comment] 2018-07-06 19:16
Hi @RayJin2000, the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.
