### ISSUE TITLE
Cannot save after make changes

### ISSUE THREAD

**Issue by dongmai** [microsoft/vscode-cosmosdb#1299] opened 2020-01-19 08:13 UTC
Repro steps:

1. Made some changes on the json file (I'm using mongo db)
2. Command+S to save then it was saying couldnt save with the error

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: MongoError
Error Message: the update operation document must contain atomic operators.

Version: 0.12.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Function.create mongodb/error.js:44:12
toError mongodb/utils.js:150:22
checkForAtomicOperators mongodb/collection_ops.js:69:12
Collection.updateOne mongodb/collection.js:700:15
Function.<anonymous> extension.bundle.js:173:38241
extension.bundle.js:173:36846
n extension.bundle.js:173:36591
Function.update extension.bundle.js:173:38092
MongoDocumentTreeItem.<anonymous> extension.bundle.js:173:38016
extension.bundle.js:173:36846
n extension.bundle.js:173:36591
MongoDocumentTreeItem.update extension.bundle.js:173:37933
MongoDocumentNodeEditor.<anonymous> extension.bundle.js:529:166526
extension.bundle.js:529:166117
n extension.bundle.js:529:165862
MongoDocumentNodeEditor.update extension.bundle.js:529:166459
CosmosEditorManager.<anonymous> extension.bundle.js:614:1057363
extension.bundle.js:614:1055569
n extension.bundle.js:614:1055314
CosmosEditorManager.updateToCloud extension.bundle.js:614:1057278
CosmosEditorManager.<anonymous> extension.bundle.js:614:1059410
s extension.bundle.js:614:1055371
```

</details>

**Comment by nturinski** [comment] 2020-01-22 01:07
Closing as a dupe of #1298.

**Closed by nturinski** 2020-01-22 01:07 UTC
