### ISSUE TITLE
Getting error while try to creat a Cosmos DB account   (steps , 6,7.8. 9  https://docs.microsoft.com/en-us/learn/modules/build-node-cosmos-app-vscode/3-exercise-create-cosmosdb-instance)

### ISSUE THREAD

**Issue by Sivprasad** [microsoft/vscode-cosmosdb#1485] opened 2020-05-21 05:35 UTC
Repro steps:

1.
2.

Action: cosmosDB.createAccount
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: 37dcfba4-2b9b-44be-b2a8-43982bb667dd, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0".

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
PollingState.getCloudError extension.bundle.js:614:115518
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-05-21 19:57
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1472

**Closed by EricJizbaMSFT** 2020-05-21 19:57 UTC
