### ISSUE TITLE
Mongo Scrapbook does not insert records to Cosmos DB 3.6 with db.collection.insert (.insertMany)

### ISSUE THREAD

**Issue by igorKOne** [microsoft/vscode-cosmosdb#1361] opened 2020-03-12 09:34 UTC
Repro steps:

1.
2.

Action: cosmosDB.executeMongoCommand
Error type: 2
Error Message: Retryable writes are not supported. Please disable retryable writes by specifying "retrywrites=false" in the connection string or an equivalent driver specific config.

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
Connection.<anonymous> mongodb/pool.js:466:61
Connection.emit events.js:203:13
processMessage mongodb/connection.js:364:10
TLSSocket.<anonymous> mongodb/connection.js:533:15
TLSSocket.emit events.js:203:13
addChunk _stream_readable.js:295:12
readableAddChunk _stream_readable.js:276:11
TLSSocket.Readable.push _stream_readable.js:210:10
TLSWrap.onStreamRead stream_base_commons.js:166:17
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-03-12 17:31
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1343

**Closed by EricJizbaMSFT** 2020-03-12 17:31 UTC
