### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by palllasz** [Microsoft/vscode-cosmosdb#1058] opened 2019-03-01 16:06 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.10.0
OS: win32

**Comment by PrashanthCorp** [comment] 2019-03-06 23:20
seems like a dupe of #508  
Is your database running? Do you have a connection to it? 

AFAICT, we do not show `127.0.0.1:27017` as an option unless we can connect to it. Did you paste this address from elsewhere?

**Comment by StephenWeatherford** [comment] 2019-03-08 19:01
We need to add more info to the error.

**Comment by PrashanthCorp** [comment] 2019-04-03 22:31
We're tracking this as part of https://github.com/Microsoft/vscode-cosmosdb/issues/866 . Closing this.

**Closed by PrashanthCorp** 2019-04-03 22:31 UTC
