### ISSUE TITLE
The input field of the document ID doesn't display when creating a document for one Mongo account 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#557] opened 2018-04-23 08:42 UTC
Repro Steps:
1. Drill down one Mongo account -> Database -> Collection.
2. Right click one collection and select 'Create Document'.
3. Check whether the input field of the document ID displays or not.

Expect:
The input field of the document ID displays.
![expect](https://user-images.githubusercontent.com/34729022/39115347-efad8874-46d0-11e8-9def-262002fa7a8a.png)

Actual:
The input field of the document ID doesn't display and no 'id' displays in the created document.
![id](https://user-images.githubusercontent.com/34729022/39115409-17132d38-46d1-11e8-8d9a-e8c8124edf4f.png)

**Comment by PrashanthCorp** [comment] 2018-04-23 16:30
Looks like a duplicate of #381.

**Comment by EricJizbaMSFT** [comment] 2018-04-23 17:27
This isn't a dupe of 381, but it is by design. See https://github.com/Microsoft/vscode-cosmosdb/issues/477

**Closed by EricJizbaMSFT** 2018-04-23 17:27 UTC
Labels: bydesign
