### ISSUE TITLE
Fail to configure firewall for the PostgreSQL Single server without any error on M1

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1972] opened 2022-04-02 02:40 UTC
**OS:** M1
**Build Version:** 20220215.11
**Regression:** Not a Regression

**Repro Steps:**

1. Create a PostgreSQL Single Server.
2. Drill down the server -> Postgres -> Click "Configure firewall to connected to...".
3. Pop up a prompt asking to continue -> Yes.
4. Check whether succeeds to configure firewall for the PostgreSQL Single server.

**Expect:**
Succeed to configure firewall for the PostgreSQL Single server.

**Actual:**
Fail to configure firewall for the PostgreSQL Single server without any error. 
https://user-images.githubusercontent.com/62053665/161362604-7229a717-c245-41f0-858e-c0b2109a92f5.mov

**More Info:**
1. Fail to configure firewall for the PostgreSQL Flexible server with an error on M1.
    <img width="334" alt="Screen Shot 2022-04-01 at 16 31 55" src="https://user-images.githubusercontent.com/62053665/161361922-72a88eca-35d4-46c0-a55f-f1e764c2606f.png">
2. Refresh or restart VS Code can not fix this issue.

**Comment by nturinski** [comment] 2022-04-07 22:42
Hi @v-mengwe  I just want to confirm, but is this only reproducing on an M1?

**Comment by v-mengwe** [comment] 2022-04-08 01:20
I tested on three machines, one Mac Inter and two M1s, the problem reproduces on all three machines. And this issue doesn't reproduce on Windows.

**Comment by alexweininger** [comment] 2022-08-18 22:48
I can't reproduce this on my Intel-based Mac.

**Comment by nturinski** [comment] 2022-09-15 22:33
@v-mengwe Can you let us know if this still reproduces? We haven't been able to reproduce it with Mac Intel.

**Comment by v-xinda** [comment] 2022-09-16 09:42
@nturinski  Verified on the latest build 20220915.4, this issue doesn't reproduce for now on M1 and Mac Intel.

**Comment by nturinski** [comment] 2022-09-16 17:18
Okay, great! Closing as resolved then.

**Closed by nturinski** 2022-09-16 17:18 UTC
Labels: bug, info-needed, AT-CTI, not repro, postgres

**Comment by alexweininger** [comment] 2022-09-16 17:19
> Okay, great! Closing as resolved then.

I'm fine closing it, but I think this issue is just unstable rather than fixed.
