### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by ttaylor** [microsoft/vscode-cosmosdb#1487] opened 2020-05-21 18:07 UTC
Repro steps:

1. Trying to create account using steps here: https://docs.microsoft.com/en-us/learn/modules/build-node-cosmos-app-vscode/3-exercise-create-cosmosdb-instance

Action: cosmosDB.createAccount
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: c605e072-7f7a-4d33-9651-91b5e2f5ebda, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Mi...

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

**Comment by EricJizbaMSFT** [comment] 2020-05-21 19:58
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1472

**Closed by EricJizbaMSFT** 2020-05-21 19:58 UTC
