### ISSUE TITLE
Scrapbook query against a regex literal fails

### ISSUE THREAD

**Issue by thanhn2001** [Microsoft/vscode-cosmosdb#835] opened 2018-09-25 22:27 UTC
Repro steps:
In a scrapbook, execute the query `db.mycollection.find({name: /Rob/})`

I expect to see a list of docs where name contains "Rob", instead I get the following error:

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 40: 'mismatched input '}' expecting '(''. Please check syntax.

Version: 0.8.0
OS: darwin

**Comment by PrashanthCorp** [comment] 2018-09-25 22:29
Hi @thanhn2001 , 
Thanks for using the extension! We appreciate your feedback! 
This is a feature request that is in PR, see #761 . The corresponding bug is at #667 . We are looking into this issue and should have a fix soon. 

I'm closing this as this is a dupe of #667.

**Closed by PrashanthCorp** 2018-09-25 22:29 UTC
