### ISSUE TITLE
Not able to create the account under MS Learn Sandbox subs.

### ISSUE THREAD

**Issue by himanshubeniwal** [microsoft/vscode-cosmosdb#1523] opened 2020-05-25 21:41 UTC
Repro steps:

1. I was completing the MS Learn module using Cosmos DB in VSCode, and it seems I am not able to create the account in my subscription. 
2. Shall I wait for some time and try this again?

Action: cosmosDB.createAccount
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: 755b4b48-39c5-4ff9-bdc9-5496192c3d60, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0,...

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

**Comment by EricJizbaMSFT** [comment] 2020-06-11 22:49
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1510

**Closed by EricJizbaMSFT** 2020-06-11 22:49 UTC
