### ISSUE TITLE
MongoDb connection to VSCode

### ISSUE THREAD

**Issue by syammohanp** [Microsoft/vscode-cosmosdb#924] opened 2018-11-05 09:15 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [cluster0-2ldgj.azure.mongodb.net:27017] on first connect [MongoError: getaddrinfo ENOTFOUND cluster0-2ldgj.azure.mongodb.net cluster0-2ldgj.azure.mongodb.net:27017]

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment] 2018-11-07 23:19
Looks like a dupe of #662 . Let us know if this helps.

**Comment by PrashanthCorp** [comment] 2019-01-23 22:01
Closing due to lack of response.

**Closed by PrashanthCorp** 2019-01-23 22:01 UTC
Labels: needs-repro, waiting-for-response
