### ISSUE TITLE
Changes in the attached database server don't reflect on the corresponding server in the tree

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#304] opened 2017-12-15 22:51 UTC
Repro : 
1. Attach a server. 
2. Add/delete a database or collection
3. Navigate to the same server on the explorer tree. 

Expected : 
The operation is reflected there too. 
Actual. 
:(

**Comment by EricJizbaMSFT** [comment] 2017-12-18 19:18
This is expected behavior. There's no mapping between attached accounts and subscription accounts.

Closing this since it has an easy workaround (hit refresh) and the user is unlikely to be using both the attached account and the subscription account at the same time.

**Closed by EricJizbaMSFT** 2017-12-18 19:18 UTC
