### ISSUE TITLE
Following 

### ISSUE THREAD

**Issue by nlksg** [microsoft/vscode-cosmosdb#1509] opened 2020-05-22 13:42 UTC
Repro steps:

Following the below document on both mac and pc fail.

1. https://docs.microsoft.com/en-us/learn/modules/build-node-cosmos-app-vscode/3-exercise-create-cosmosdb-instance
2.

Action: cosmosDB.createAccount
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: e7d9ec0d-2b8f-4a88-aa6f-95c2479bba4f, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Mi...

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

**Comment by nturinski** [comment] 2020-06-04 19:00
Dupe of #1472

**Closed by nturinski** 2020-06-04 19:00 UTC
