### ISSUE TITLE
Language client is not ready yet

### ISSUE THREAD

**Issue by dumasss163** [microsoft/vscode-cosmosdb#1351] opened 2020-03-10 03:37 UTC
Repro steps:

1.just click "Connect to a database" and pick a mongodb database which connects and query data well in the "azure:cosmos db" browser
2. the error occurs, and there is another error in the output: [Error - xxx] Starting client failed \n 9

Action: cosmosDB.connectMongoDB
Error type: Error
Error Message: Language client is not ready yet

Version: 0.12.1
OS: win32
Product: Visual Studio Code
Product Version: 1.43.0
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
LanguageClient.sendRequest vscode-languageclient/client.js:1615:19
MongoDBLanguageClient.<anonymous> extension.bundle.js:614:1081341
extension.bundle.js:614:1080477extension.bundle.js:614:1080477
n extension.bundle.js:614:1080222
MongoDBLanguageClient.connect extension.bundle.js:614:1081289
Object.<anonymous> extension.bundle.js:614:1078327
a extension.bundle.js:614:1074782
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-03-10 17:37
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1334

**Closed by EricJizbaMSFT** 2020-03-10 17:37 UTC
