### ISSUE TITLE
Creating Mongo database shouldn't require me to create Mongo collection

### ISSUE THREAD

**Issue by Omelianenko** [Microsoft/vscode-cosmosdb#848] opened 2018-10-04 01:55 UTC
It's possible to create SQL database without collection(press Esc when collection name is requesting in the node picker section), but it's not possible with Mongo. 
SQL database is being created right after database name has entered, but Mongo is being created only after collection name has entered.

**Comment by Omelianenko** [comment] 2018-10-04 19:00
I think that it's fine to create a database without collections, so I prefer not to ask about collections while creating a database at all. But I don't like the idea of creating any collection automatically.

**Comment by StephenWeatherford** [comment] 2018-10-04 21:13
Never understood why the portal asks for creating collections instead of databases (but then requires you to give a database name, too).  That said, why exact behavior change are you suggesting?

**Comment by StephenWeatherford** [comment] 2018-10-04 21:56
Portal doesn't like databases without collections - it never shows databases by themselves, just collections, so a database without a collection doesn't appear on the portal.  I suspect Mongo may feel the same way.  @PrashanthCorp?

cc @fiveisprime

**Comment by PrashanthCorp** [comment] 2018-10-04 23:54
From my understanding, this is where Cosmos(Mongo mode) and MongoDB diverge. 

Inside mongo shell, the behavior is to lazily create a database only when it is needed (a collection is created). 
![image](https://user-images.githubusercontent.com/30420973/46509111-bad16480-c7f5-11e8-8d7f-235ed00471a2.png)
In cosmosdb however (both SQL and Mongo), the creation of database is eager
![image](https://user-images.githubusercontent.com/30420973/46509134-d8063300-c7f5-11e8-90c0-15cc8c6ca843.png)

Note that `testNewDB` contains no collections on creation.

**Comment by StephenWeatherford** [comment] 2018-10-12 22:28
Thanks for bringing this up, but we don't feel this is important enough to change. If you disagree, please indicate how it negatively impacts customers.  Thx.

**Comment by EricJizbaMSFT** [comment] 2018-10-15 16:08
I disagree so re-opening. I think we're asking users to create something that is usually created programatically. I will repeat what I said earlier:  in the [node-todo](https://github.com/scotch-io/node-todo) sample project that Matt uses to demo, we give it a connection string to a database and the app creates the 'todos' collection automatically. That's the only "real" world example mentioned in this thread, so I think "it's annoying" is a valid enough reason to fix this.

Even if you're just messing around in a scrapbook, Mongo will automatically create collections if you run commands like this:
```
db.newColl.insertMany([

])
```

**Comment by StephenWeatherford** [comment] 2018-10-15 18:34
@PrashanthCorp?

**Comment by PrashanthCorp** [comment] 2018-10-15 19:03
Just to verify if it was possible, I re-ran an experiment. 
I ran a local Mongo instance (so that I'm using Mongo and not Cosmos' Mongo).  I tried to create a database by proxy - create a mock collection and delete it. 
Here's what I did: 
1. List current databases - 
local , admin
2. I created a database _testDB_
result: Ok. DB still doesn't show up, as expected. 
3. Created a collection,
Result: ok. 
4. listed the databases
Result: testDB shows up
5. Listed collections within created DB
Result: Collection shows up
6. Dropped the collection
Result: ok
7. Listed the DBs
TestDB no longer shows up!
 
![image](https://user-images.githubusercontent.com/30420973/46971232-45c12300-d070-11e8-9d48-538cc171805d.png)


So not only does Mongo lazily create a DB, it also deletes (or at the very least unlists) a DB with no collections contained. So what you're asking is pretty much impossible inside local Mongo, and Mongo has "made it annoying" by design. :-| 
Making this consistent across types of accounts is impossible if we're agnostic to where the database resides. 

There's another important aspect that is being missed here: creating collections **will** cost money in Cosmos. I personally would be on the side of avoiding creating a collection without user-request.  Given that our logic is agnostic to these use cases, there is a chance we're costing the user some money with your approach which could be avoided. 


I'm now more convinced that we can't fix this unless we decide our logic should be aware of where the database is residing. @fiveisprime @jinglouMSFT  what do you think?

**Comment by EricJizbaMSFT** [comment] 2018-10-15 19:12
> creating collections will cost money in Cosmos.

To me that implies we should lazy-create collections so that we're not forcing users to spend money right away. My suggestion sounds like it's _saving_ the user money.

I'll have to try the local scenario before I can comment on that more.

**Comment by PrashanthCorp** [comment] 2018-10-15 21:37
> To me that implies we should lazy-create collections so that we're not forcing users to spend money right away. My suggestion sounds like it's saving the user money.

In SQL: We don't create a collection right away. So we currently don't cost them more money. 
In Mongo: We ask to create a collection since there's no other way to instantiate a database, AFAIK. If we find a way to fix this, we'll triage it. 

>I actually think the mongo behavior is correct and the sql behavior is broken. If I hit 'esc' it should cancel the whole process - not just the creation of the collection

Your initial suggestion answers why I pointed out operations costing money.

**Comment by EricJizbaMSFT** [comment] 2018-10-15 21:45
First of all this is the "Cosmos DB" extension, not the "Mongo" extension so it's totally fine to have special cases for Cosmos DB.

Secondly I don't think you even need to special case this. We could do a virtual database like Storage explorer does virtual directories:
![screen shot 2018-10-15 at 2 20 32 pm](https://user-images.githubusercontent.com/11282622/46980168-980e3e00-d088-11e8-8007-431d166ac8ea.png)

Again - I'm prioritizing "real world" scenarios here. For Matt's node-todo app he only needs to copy the connection string to the database and then everything else will be created programatically. It doesn't matter if the database actually exists in Mongo as long as he can get that connection string.

**Comment by Omelianenko** [comment] 2018-10-30 01:10
Can we just for now make the creating behavioral the same as SQL? I feel like it's a better solution than what we have now: if you click ESC when it asks collection name, the database is being created

**Comment by EricJizbaMSFT** [comment] 2018-11-13 23:30
This was fixed by https://github.com/Microsoft/vscode-cosmosdb/pull/891. You still have to create a collection by default when using the context menu entry point, but you don't have to create a collection using the node picker entry point (the scenario we care about for App Service Connections). Seems like a good compromise

**Closed by EricJizbaMSFT** 2018-11-13 23:30 UTC
