### ISSUE TITLE
connection to mongodb 

### ISSUE THREAD

**Issue by AswiniThota** [Microsoft/vscode-cosmosdb#938] opened 2018-11-11 12:01 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment] 2018-11-12 01:42
Looks like a dupe of #662.

**Comment by PrashanthCorp** [comment] 2019-01-23 22:02
Closing due to lack of response.

**Closed by PrashanthCorp** 2019-01-23 22:02 UTC
Labels: waiting-for-response
