### ISSUE TITLE
Cosmos broken when updating cosmosdb plugin

### ISSUE THREAD

**Issue by antjamesbird** [microsoft/vscode-cosmosdb#1300] opened 2020-01-20 15:29 UTC
Repro steps:

1. Tried saving my local DB
2. Getting this error

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: MongoError
Error Message: the update operation document must contain atomic operators.

Version: 0.12.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.0
Language: en

<details>
<summary>Call Stack</summary>

```
Function.create mongodb/error.js:44:12
toError mongodb/utils.js:150:22
checkForAtomicOperators mongodb/collection_ops.js:69:12
Collection.updateOne mongodb/collection.js:700:15
Function.<anonymous> extension.bundle.js:173:38241
module.exports.n extension.bundle.js:173:36846
module.exports.n extension.bundle.js:173:36591
Function.update extension.bundle.js:173:38092
MongoDocumentTreeItem.<anonymous> extension.bundle.js:173:38016
module.exports.n extension.bundle.js:173:36846
module.exports.n extension.bundle.js:173:36591
MongoDocumentTreeItem.update extension.bundle.js:173:37933
MongoDocumentNodeEditor.<anonymous> extension.bundle.js:529:166526
module.exports.n extension.bundle.js:529:166117
module.exports.n extension.bundle.js:529:165862
MongoDocumentNodeEditor.update extension.bundle.js:529:166459
CosmosEditorManager.<anonymous> extension.bundle.js:614:1057363
module.exports.n extension.bundle.js:614:1055569
module.exports.n extension.bundle.js:614:1055314
CosmosEditorManager.updateToCloud extension.bundle.js:614:1057278
```

</details>

**Comment by nturinski** [comment] 2020-01-22 01:12
Closing as a dupe of #1298.

**Closed by nturinski** 2020-01-22 01:12 UTC
