### ISSUE TITLE
how can i solve it?

### ISSUE THREAD

**Issue by cmrdoguzhan** [Microsoft/vscode-cosmosdb#739] opened 2018-07-02 09:19 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.7.2
OS: win32

**Comment by PrashanthCorp** [comment] 2018-07-02 17:59
Thanks for reporting the issue! We really appreciate your feedback. :) 

From a first look, it looks like you're trying to connect to a local mongodb instance. 
Please let us know if [this comment](https://github.com/Microsoft/vscode-cosmosdb/issues/662#issuecomment-395891819) helps. 
It currently looks like this issue is a duplicate of #662.

**Comment by PrashanthCorp** [comment] 2018-07-02 21:30
I'm closing this as I feel this is a dupe of #662. 

Please feel free to reopen if the problem still persists, we'd love to hear your scenario.

**Closed by PrashanthCorp** 2018-07-02 21:30 UTC

**Comment by PrashanthCorp** [comment] 2018-07-06 19:15
Hi @cmrdoguzhan ,  the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.

**Comment by cmrdoguzhan** [comment] 2018-07-17 08:47
I fixed it thanks @PrashanthCorp
