### ISSUE TITLE
Pop up an error when updating a Mongo DB document

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1225] opened 2019-10-25 07:18 UTC
**OS**: Win10 & Mac
**Build Version:** [20191024.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11529)

**Repro Steps:**
1. Right click one Mongo DB and new a database --> collection -->document.
2. Open the document and edit the auto-generated filed.
3. "Ctrl /Command + S" to save the update --> Pop up below notification. -->Select "Upload".
![image](https://user-images.githubusercontent.com/34729092/67550951-58b60b00-f73a-11e9-9bb2-d3d166ec6084.png)

**Expect:**
Succeed to update without any error.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/34729092/67550988-6cfa0800-f73a-11e9-931f-d312d4b2528d.png)

**More Info:**
There is no other operation at the same time.

**Comment by nturinski** [comment] 2019-11-13 23:29
We are unable to reproduce this.  Are there any other steps you could include?  What specifically are you editing in the document?  Which auto-generated field?

**Comment by v-dantch** [comment] 2019-11-20 09:01
Hi Nathan, thanks for your response. Please get more info from below. Hope this will help you.

**Repro Steps:**
Create a new document --> Edit as below
![image](https://user-images.githubusercontent.com/34729092/69224243-2a034700-0bb7-11ea-9326-a953f0437073.png)
Ctrl + S to save it --> Select "Upload" when asked whether to save or not.
![image](https://user-images.githubusercontent.com/34729092/69223400-405cd300-0bb6-11ea-9f93-e29dc1d005aa.png)
Then pop up below error:
![image](https://user-images.githubusercontent.com/34729092/69224129-f1fc0400-0bb6-11ea-8042-d384ad1dceea.png)

**Comment by v-ruizh** [comment] 2019-12-17 10:14
This issue also reproduces on the latest build [20191216.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13159&view=results), reopen it.

**Comment by nturinski** [comment] 2020-01-22 18:37
This is actually this error: https://github.com/microsoft/vscode-cosmosdb/issues/1298

I guess when I tested it back in November, I must have used an old version and forgot to follow up on this when I got back 😭 Sorry about this error

**Comment by nturinski** [comment] 2020-01-23 21:54
Fixed by https://github.com/microsoft/vscode-cosmosdb/pull/1304

**Closed by nturinski** 2020-01-23 21:54 UTC
Labels: AT-CTI
