### ISSUE TITLE
trying to import data via a json file...

### ISSUE THREAD

**Issue by CaptainAndy01** [microsoft/vscode-cosmosdb#1796] opened 2021-01-10 22:26 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

Does this occur consistently? 
Repro steps:

1.
2.

Action: cosmosDB.importDocument
Error type: Error
Error Message: key $oid must not start with '$'

Version: 0.15.1
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
serializeInto bson/serializer.js:915:19
serializeObject bson/serializer.js:347:18
serializeInto bson/serializer.js:941:17
serializeObject bson/serializer.js:347:18
serializeInto bson/serializer.js:727:17
serializeObject bson/serializer.js:347:18
serializeInto bson/serializer.js:941:17
BSON.serialize bson/bson.js:64:28
Msg.serializeBson mongodb/msg.js:126:22
Msg.makeDocumentSegment mongodb/msg.js:118:33
Msg.toBin mongodb/msg.js:104:25
MessageStream.writeCommand mongodb/message_stream.js:55:28
Connection.write mongodb/connection.js:368:26
_command mongodb/command.js:120:10
command mongodb/command.js:28:5
writeCommand mongodb/write_command.js:47:3
Object.insert mongodb/index.js:6:5
Connection.insert mongodb/connection.js:187:8
mongodb/server.js:483:13
Object.callback mongodb/connection_pool.js:345:7
mongodb/connection_pool.js:499:23
mongodb/connection_pool.js:425:7
callback mongodb/connect.js:75:5
mongodb/connect.js:148:11
MessageStream.messageHandler mongodb/connection.js:277:5
MessageStream.emit events.js:223:5
processIncomingData mongodb/message_stream.js:144:12
MessageStream._write mongodb/message_stream.js:42:5
doWrite _stream_writable.js:435:12
writeOrBuffer _stream_writable.js:419:5
MessageStream.Writable.write _stream_writable.js:309:11
TLSSocket.ondata _stream_readable.js:728:22
TLSSocket.emit events.js:223:5
addChunk _stream_readable.js:309:12
readableAddChunk _stream_readable.js:290:11
TLSSocket.Readable.push _stream_readable.js:224:10
TLSWrap.onStreamRead stream_base_commons.js:181:23
```

</details>

**Comment by nturinski** [comment] 2021-01-11 17:56
Closing as a dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1797

**Closed by nturinski** 2021-01-11 17:56 UTC
