### ISSUE TITLE
Cannot connect to local Cosmos DB Emulator (Windows) due to error "self signed certificate"

### ISSUE THREAD

**Issue by DaveAurionix** [Microsoft/vscode-cosmosdb#336] opened 2018-01-24 11:28 UTC
When trying to "Attach Database Account" and entering the local emulator connection string, an error pops up simply saying "self signed certificate".  Setting "[http.proxyStrictSSL = false](https://stackoverflow.com/questions/36506539/how-do-i-get-visual-studio-code-to-trust-our-self-signed-proxy-certificate)" in the Visual Studio Code settings file didn't help.

The emulator's connection string I used was "AccountEndpoint=https://localhost:8081;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==" (which is the public emulator key from [Microsoft's documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator)).

**Comment by EricJizbaMSFT** [comment] 2018-01-24 16:53
@DaveAurionix we plan to have a fix for this in the next release

Closing as dupe of https://github.com/Microsoft/vscode-cosmosdb/issues/215

**Closed by EricJizbaMSFT** 2018-01-24 16:53 UTC
