### ISSUE TITLE
 self signed certificate Error

### ISSUE THREAD

**Issue by willsonwangrft** [microsoft/vscode-cosmosdb#1536] opened 2020-05-27 13:34 UTC
Repro steps:

1. reset Data
2. restart emulator
3. connect via VS code extension

Action: cosmosDB.createGraphDatabase
Error type: DEPTH_ZERO_SELF_SIGNED_CERT
Error Message: self signed certificate

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure _tls_wrap.js:1317:34
TLSSocket.emit events.js:203:13
TLSSocket._finishInit _tls_wrap.js:792:8
TLSWrap.ssl.onhandshakedone _tls_wrap.js:606:12
```

</details>

**Comment by neelip** [comment] 2020-07-09 22:20
Duplicate of #980

**Closed by neelip** 2020-07-09 22:20 UTC
