### ISSUE TITLE
Can't connect to Mongo servers - "Couldn't start client Mongo Language Server"

### ISSUE THREAD

**Issue by believetech-orw** [microsoft/vscode-cosmosdb#1352] opened 2020-03-10 04:27 UTC
Repro steps:

Mac OS version 10.14.6, from a new terminal window:

1.cd ~
2.mkdir vscode-test
3.cd vscode-test/
4.code .
5.[CMD-SHIFT-A], or click on the "Azure" icon in the Extensions bar to open the vscode Azure CosmosDB Extension
6.Observe "Output" message: `[Error - 11:46:02 PM] Starting client failed`
7 Observe "Notifications" popup: `Couldn't start client Mongo Language Server...Source: Azure Cosmos DB (Extension)`
8.In COSMOSDB panel, Click "Attached Database Accounts" to expand the list of connected Mongo servers (demonstrate that connections seem to be working)
9.Click a mongo connection to expand to a list of schemas
10.On a collection, 2-finger click (on a Mac) and select "Connect"
11.Observe `Language client is not ready yet...Source: Azure Cosmos DB (Extension)`

Action: cosmosDB.connectMongoDB
Error type: Error
Error Message: Language client is not ready yet

Version: 0.12.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
LanguageClient.sendRequest vscode-languageclient/client.js:1615:19
MongoDBLanguageClient.<anonymous> extension.bundle.js:614:1081341
extension.bundle.js:614:1080477
n extension.bundle.js:614:1080222
MongoDBLanguageClient.connect extension.bundle.js:614:1081289
Object.<anonymous> extension.bundle.js:614:1078327
a extension.bundle.js:614:1074782
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-03-10 17:37
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1334

**Closed by EricJizbaMSFT** 2020-03-10 17:37 UTC
