### ISSUE TITLE
aggregate queries displays syntax error

### ISSUE THREAD

**Issue by martynas-m** [Microsoft/vscode-cosmosdb#708] opened 2018-06-21 13:07 UTC
Repro steps:
create aggregate query. will not run. 

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 22, text '$match'. Please check syntax.

Version: 0.7.2
OS: linux

**Comment by PrashanthCorp** [comment] 2018-06-25 17:46
Hi Martyn, 

Do you have the exact query you tried running? That would help us figure out the root issue. :) 

Please also check that you have all strings in double-quotes. See #466 and #467 for existing issues that could be the cause for your issue.

**Comment by StephenWeatherford** [comment] 2018-06-29 21:36
@martynas-m I'm pretty sure this will be fixed by #728, which should release in about a week.

**Comment by StephenWeatherford** [comment] 2018-06-29 21:37
Closing for now.  Please feel free to reopen if the next release does not fix it for you.

**Closed by StephenWeatherford** 2018-06-29 21:37 UTC
Labels: waiting-for-response

**Comment by PrashanthCorp** [comment] 2018-07-06 19:15
Hi Martyn, the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.
