### ISSUE TITLE
DB Creation Error

### ISSUE THREAD

**Issue by abeniang** [microsoft/vscode-cosmosdb#1108] opened 2019-05-06 18:01 UTC
Repro steps:

1.
2.

Action: cosmosDB.createMongoDatabase
Error type: Error
Error Message: Cannot resolve tree item for element 1//subscriptions/9a3a97be-404d-4d2b-bf38-16d47d8f5289/resourceGroups/AkbtRG/providers/Microsoft.DocumentDB/databaseAccounts/nodepilotcosmosdbaccount/dhp0

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
define.resolveTreeNode.a.asPromise.then.then.e.getChildren.then extensionHostProcess.js:464:664
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by PrashanthCorp** [comment] 2019-05-22 22:24
Looks like a dupe of #1119

**Closed by PrashanthCorp** 2019-05-22 22:24 UTC
