### ISSUE TITLE
Error with "new Date()" in VSCODE with Azure Databases

### ISSUE THREAD

**Issue by clbsoftwarehardware** [microsoft/vscode-cosmosdb#1602] opened 2020-07-03 19:24 UTC
Does this occur consistently? YES
Repro steps:

1.Wrote this script:
`db.alumnos.aggregate({
     $project: {
          ts: { "date": new Date() }
     }
})`
just to get the current date. When I executed, the extension show this:
`Unrecognized node type encountered. Could not parse newDate as part of newDate()`

2. When I use the same script in MongoDB shell shows the current time:
```
db.alumnos.aggregate({ $project: { ts: {"date": new Date() }}  })
{ "_id" : ObjectId("5efdfe17e9d4be42a03287ec"), "ts" : { "date" : ISODate("2020-07-03T19:17:33.787Z") } }
```

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 43: 'Unrecognized node type encountered. Could not parse newDate as part of newDate()'. Please check syntax.

Version: 0.13.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.1
Language: es

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:245:238707extension.bundle.js:245:238707
extension.bundle.js:245:237638extension.bundle.js:245:237638
i extension.bundle.js:245:237324
executeCommand extension.bundle.js:245:238224
Object.<anonymous> extension.bundle.js:245:242011
extension.bundle.js:245:237638extension.bundle.js:245:237638
i extension.bundle.js:245:237324
Object.executeCommandFromText extension.bundle.js:245:241904
Object.<anonymous> extension.bundle.js:626:1363069
fulfilled extension.bundle.js:626:1357801
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by neelip** [comment] 2020-07-09 22:17
Duplicate of #1060

**Closed by neelip** 2020-07-09 22:17 UTC
