### ISSUE TITLE
The result is inconsistent after executing 'db.version()' in the scrapbook between MongoDB account and MongoDB emulator

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1939] opened 2021-10-21 09:46 UTC
**OS:** Win10
**Build Version:** 20211019.1
**Mongo DB Version:** 5.0.2
**Cosmos DB Emulator Version:** 2.14.3
**Regression:** Not a regression

**Repro Steps:**
1. Create a MongoDB account -> Create a database -> Connect the database -> Create new mongo scrapbook.
2. Execute `db.version()` in the scrapbook -> Check the result.
3. Attach the MongoDB emulator -> Create a database -> Connect the database -> Create new mongo scrapbook.
4. Execute `db.version()` in the scrapbook -> Check the result.
5. Check whether the result is consistent between the step 2 and step 4.

**Expect:**
The result is consistent between the step 2 and step 4.

**Actual:**
The result is inconsistent between the step 2 and step 4.
MongoDB account: Show **4.0.0** in the result after executing `db.version()` in the scrapbook.
MongoDB emulator : Show **3.2.0** in the result after executing `db.version()` in the scrapbook.
![actual02](https://user-images.githubusercontent.com/57662131/138249563-909e1f5a-e33c-407a-bde0-8a720d2d90ba.gif)

**Comment by wwlorey** [comment] 2022-01-20 23:56
Closing as duplicate of https://github.com/microsoft/vscode-cosmosdb/issues/1207

**Comment by wwlorey** [comment] 2022-01-20 23:57
Closing as duplicate of https://github.com/microsoft/vscode-cosmosdb/issues/1207

**Closed by wwlorey** 2022-01-20 23:56 UTC
Labels: duplicate, AT-CTI
