### ISSUE TITLE
Error Message: TextEditor(vs.editor.ICodeEditor:1,$model23) has been disposed

### ISSUE THREAD

**Issue by stizzle123** [Microsoft/vscode-cosmosdb#640] opened 2018-05-24 08:37 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.openDocument
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:1,$model23) has been disposed

Version: 0.7.1
OS: win32

**Comment by PrashanthCorp** [comment] 2018-05-24 19:12
Hi Arifayan, 

Would you be able to give us more detailed reproduction steps. We currently cannot reproduce your error on our end. 

Thanks for using our product and filing feedback!

**Comment by StephenWeatherford** [comment] 2018-05-30 22:41
I think it may happen when you open a window and close it quickly...?

**Comment by StephenWeatherford** [comment] 2018-10-03 21:20
Closing due to lack of response.  Please re-open if you have more information on how we can reproduce this, thanks.

**Closed by StephenWeatherford** 2018-10-03 21:20 UTC
Labels: P3, needs-repro
