### ISSUE TITLE
Azure Cosmos DB Extension Error 

### ISSUE THREAD

**Issue by usama4414** [microsoft/vscode-cosmosdb#1484] opened 2020-05-21 02:51 UTC
Repro steps:

1.
2.

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: PreconditionFailed
Error Message: Operation cannot be performed because one of the specified precondition is not met., 
RequestStartTime: 2020-05-21T02:50:54.5712129Z, RequestEndTime: 2020-05-21T02:50:54.5712129Z,  Number of regions attempted:1
ResponseTime: 2020-05-21T02:50:54.5712129Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-japaneast1-fd3.documents.azure.com:14037/apps/e5c37180-ee17-44d3-9f44-ab2999ab422f/services/0d4f0406-40b8-4982-b2cd-593bf0a86ee7/partitions/11155a83-ed3e-4434-a864-8fdda2bcbdab/replicas/132344427047456663p/, LSN: 11, GlobalCommittedLsn: 11, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 412, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: 11, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Replace
, Microsoft.Azure.Documents.Common/2.11.0

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

**Comment by wwlorey** [comment] 2020-07-16 22:14
Please add steps to reproduce the issue

**Comment by wwlorey** [comment] 2020-07-16 22:19
Duplicate of https://github.com/microsoft/vscode-cosmosdb/issues/1473

**Closed by wwlorey** 2020-07-16 22:19 UTC
Labels: needs more info
