### ISSUE TITLE
An error occurs after expanding the resource group contains a database server

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2012] opened 2022-05-17 03:00 UTC
**OS:** Win10
**Azure Database Build Version:** 20220516.20
**Resource Goup Build Version:** 20220516.8

**Repro Steps:**
1. Create a database server.
2. Expand the resource group contains this database server.
3. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/168714128-68cb5092-2aba-4c1b-82ee-5e06cfcf4da6.png)

**More Info:**
This issue also reproduces when clicking "Click to view resource" in "ACTIVITYLOG" to focus the database server.

**Comment by alexweininger** [comment] 2022-05-17 22:43
@nturinski was #2010 trying to fix this? The build they found this bug on was before that PR was merged.

**Closed** 2022-05-18 01:49 UTC
Labels: bug, AT-CTI, needs-verification

**Comment by nturinski** [comment] 2022-05-18 17:43
> @nturinski was #2010 trying to fix this? The build they found this bug on was before that PR was merged. I can't reproduce this myself on the latest builds.

Sorry for the late reply.  Yeah, it was intended to fix this (and the create not working, I believe)
