### ISSUE TITLE
Updating a mongo collection does not add/remove IDs from explorer

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-cosmosdb#262] opened 2017-12-06 21:26 UTC
If you open a Mongo DB collection and add or delete a document and then update the collection, the data does not persist.

**Comment by PrashanthCorp** [comment] 2017-12-20 01:17
Can you define what you mean by the data not persisting? 

If you refresh the collection node, it shows up to me.

**Comment by PrashanthCorp** [comment] 2018-01-03 00:42
Looks like a dupe of #312

**Comment by EricJizbaMSFT** [comment] 2018-01-25 19:26
This was by-design when originally implemented. However, it's a feature we could consider adding

**Closed** 2018-09-26 23:19 UTC
Labels: feature, wontfix
