### ISSUE TITLE
Creation of Document DB in CosmosDB using Visual studio failed

### ISSUE THREAD

**Issue by saikrishnapujari** [microsoft/vscode-cosmosdb#1524] opened 2020-05-25 23:16 UTC
Repro steps:

1.Select subscription
2.Created DB - select Cosmos DB for Mongo db

Action: cosmosDB.createAccount
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: d5235ce3-e205-427f-aa68-97b83c275373, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Mi...

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

**Comment by EricJizbaMSFT** [comment] 2020-06-11 22:49
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1510

**Closed by EricJizbaMSFT** 2020-06-11 22:49 UTC
